### ISSUE TITLE
Add option to changue subtitle size

### ISSUE THREAD

**Issue by limewire** [feross/webtorrent-desktop#1144]
I think i should have an option to change the subtitle font size in the "**Playback**" menu. 
Looks very small in TV.

**Comment by brunoti** [comment]
You can change the font size by styling the subtitle shadow dom with this code:

```css
video::-webkit-media-text-track-display {
  font-size: 50px;
}
```

I can do a PR if this ideia fits on the project:
- 2 buttons (plus/minus) controls the style tag with the code above by adding/subtracting 10px on the font-size.
